---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-cm
  namespace: vote
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"
  OPTION_A: luffy 
  OPTION_B: zoro
